import type { RefObject, MutableRefObject } from 'react';
import type { CardOnBoard, PlayerSummary, Counter } from '../store/useGameStore';
import type { Point } from '../store/useGameStore';

export interface BoardViewProps {
  boardRef: RefObject<HTMLDivElement | null>;
  board: CardOnBoard[];
  allPlayers: PlayerSummary[];
  playerId: string;
  playerName: string;
  battlefieldCards: CardOnBoard[];
  libraryCards: CardOnBoard[];
  cemeteryCards: CardOnBoard[];
  exileCards: CardOnBoard[];
  storeLibraryPositions: Record<string, Point>;
  storeCemeteryPositions: Record<string, Point>;
  storeExilePositions: Record<string, Point>;
  showHand: boolean;
  dragStateRef: RefObject<{ cardId: string; offsetX: number; offsetY: number; startX: number; startY: number; hasMoved: boolean } | null>;
  draggingLibrary: { playerName: string; offsetX: number; offsetY: number; startX: number; startY: number } | null;
  draggingCemetery: { playerName: string; offsetX: number; offsetY: number; startX: number; startY: number } | null;
  draggingExile: { playerName: string; offsetX: number; offsetY: number; startX: number; startY: number } | null;
  ownerName: (card: CardOnBoard) => string;
  handleCardClick: (card: CardOnBoard, event: React.MouseEvent) => void;
  handleCardContextMenu: (card: CardOnBoard, event: React.MouseEvent) => void;
  handleCardZoom: (card: CardOnBoard, event: React.PointerEvent) => void;
  startDrag: (card: CardOnBoard, event: React.PointerEvent) => void;
  zoomedCard: string | null;
  setZoomedCard: (cardId: string | null) => void;
  setLibraryContainerRef?: (playerName: string, element: HTMLDivElement | null) => void;
  startLibraryDrag: (targetPlayerName: string, event: React.PointerEvent) => void;
  startCemeteryDrag: (targetPlayerName: string, event: React.PointerEvent) => void;
  startExileDrag: (targetPlayerName: string, event: React.PointerEvent) => void;
  changeCardZone: (cardId: string, newZone: 'battlefield' | 'hand' | 'library' | 'cemetery' | 'exile', position: Point, libraryPlace?: 'top' | 'bottom' | 'random') => void;
  detectZoneAtPosition: (x: number, y: number) => { zone: 'battlefield' | 'hand' | 'library' | 'cemetery' | 'exile' | null; ownerId?: string };
  reorderHandCard: (cardId: string, newIndex: number) => void;
  reorderLibraryCard: (cardId: string, newIndex: number) => void;
  dragStartedFromHandRef: RefObject<boolean>;
  handCardPlacedRef: RefObject<boolean>;
  setContextMenu: (menu: { x: number; y: number; card: CardOnBoard } | null) => void;
  setLastTouchedCard: (card: CardOnBoard | null) => void;
  getPlayerArea: (ownerId: string) => { x: number; y: number; width: number; height: number } | null;
  getLibraryPosition: (playerName: string) => Point | null;
  getCemeteryPosition: (playerName: string) => Point | null;
  getExilePosition: (playerName: string) => Point | null;
  handDragStateRef: MutableRefObject<{
    draggingHandCard: string | null;
    handCardMoved: boolean;
    previewHandOrder: number | null;
    dragPosition: Point | null;
    dragStartPosition: Point | null;
    dragOffset: Point | null;
  }>;
  addEventLog: (type: string, message: string, cardId?: string, cardName?: string, details?: Record<string, unknown>) => void;
  viewMode: 'individual' | 'separated';
  convertMouseToSeparatedCoordinates?: (mouseX: number, mouseY: number, playerId: string, rect: DOMRect) => { x: number; y: number } | null;
  convertMouseToUnifiedCoordinates?: (mouseX: number, mouseY: number, rect: DOMRect) => { x: number; y: number };
  counters: Counter[];
  moveCounter: (counterId: string, position: Point) => void;
  modifyCounter: (counterId: string, delta?: number, deltaX?: number, deltaY?: number, setValue?: number, setX?: number, setY?: number) => void;
  removeCounterToken: (counterId: string) => void;
  mulligan?: (playerId: string) => void;
  playerHandCards?: CardOnBoard[];
  flipCard: (cardId: string) => void;
}

export const BASE_BOARD_WIDTH = 1920;
export const BASE_BOARD_HEIGHT = 1080;
export const CARD_WIDTH = 150;
export const CARD_HEIGHT = 210;
